"""
SQLAlchemy database models for logging state, predictions, and trades.
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Asset(Base):
    """Stores information about an asset (Stock/Option/Mutual Fund)"""
    __tablename__ = 'assets'
    
    ticker = Column(String(20), primary_key=True)
    name = Column(String(100))
    asset_type = Column(String(20)) # 'Equity', 'Option', 'MutualFund'
    sector = Column(String(50))
    is_active = Column(Boolean, default=True)
    last_updated = Column(DateTime, default=datetime.utcnow)

class MarketData(Base):
    """Stores daily cache of OHLCV to reduce API calls"""
    __tablename__ = 'market_data'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(20), ForeignKey('assets.ticker'), index=True)
    date = Column(DateTime, index=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(Integer)
    adjusted_close = Column(Float)

class Prediction(Base):
    """Stores historical model predictions for self-learning"""
    __tablename__ = 'predictions'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(20), ForeignKey('assets.ticker'), index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    model_name = Column(String(50))  # 'LSTM', 'Transformer', 'Ensemble'
    forecast_days = Column(Integer)  # e.g., 5
    predicted_price = Column(Float)
    predicted_direction = Column(String(10)) # 'UP', 'DOWN', 'FLAT'
    confidence = Column(Float)       # 0.0 to 1.0
    actual_price_result = Column(Float, nullable=True) # Filled later
    was_correct = Column(Boolean, nullable=True)       # Filled later

class SentimentRecord(Base):
    """Stores News Sentiment analysis results"""
    __tablename__ = 'sentiment_records'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(20), index=True) # Can be a stock or 'MARKET'
    timestamp = Column(DateTime, default=datetime.utcnow)
    source = Column(String(100))
    headline = Column(String(500))
    sentiment_score = Column(Float)      # -1.0 to 1.0
    sentiment_label = Column(String(10)) # 'Positive', 'Negative', 'Neutral'
    confidence = Column(Float)

class TradeRecommendation(Base):
    """Final recommendations generated by the system"""
    __tablename__ = 'recommendations'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(20), ForeignKey('assets.ticker'), index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    strategy_type = Column(String(50)) # 'Intraday', 'Swing', 'Options'
    action = Column(String(10))        # 'BUY', 'SELL', 'HOLD'
    entry_price = Column(Float)
    target_price_1 = Column(Float)
    target_price_2 = Column(Float, nullable=True)
    stop_loss = Column(Float)
    confidence = Column(Float)
    reasoning = Column(String(1000))
    status = Column(String(20), default='ACTIVE') # 'ACTIVE', 'CLOSED_PROFIT', 'CLOSED_LOSS', 'EXPIRED'
    closing_price = Column(Float, nullable=True)
    pnl_percent = Column(Float, nullable=True)

class ModelMetrics(Base):
    """Tracks accuracy of models over time (updated by Self-Learning Agent)"""
    __tablename__ = 'model_metrics'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    model_name = Column(String(50))
    ticker = Column(String(20)) # Specific stock or 'ALL'
    accuracy = Column(Float)  # Win rate
    mse = Column(Float)       # Mean Squared Error for price predictions
    samples_count = Column(Integer)
