"""
Agent 2: Data Processing
Responsible for cleaning data, handling NaNs, mapping technical indicators,
and generating feature matrices for the ML models.
"""

from agents.base_agent import BaseAgent
from utils.indicators import add_all_indicators
from utils.data_utils import normalize_features
from database.db_manager import db
from database.models import MarketData
import pandas as pd

class DataProcessingAgent(BaseAgent):
    
    def __init__(self):
        super().__init__("DataProcessing")
        self.session = None

    def initialize(self) -> bool:
        try:
            self.session = db.get_session()
            return True
        except Exception as e:
            self.logger.error(f"Failed to initialize: {e}")
            return False

    def execute(self, ticker: str, normalize: bool = True, **kwargs) -> dict:
        """
        Extracts raw data for a ticker, cleans it, adds indicators.
        Returns the processed DataFrame.
        """
        if not self.session:
            self.initialize()
            
        self.logger.info(f"Processing data for {ticker}")
        
        try:
            # 1. Fetch raw data from DB
            # Fetch order by date ASC to ensure correct time series
            query = self.session.query(MarketData)\
                .filter(MarketData.ticker == ticker)\
                .order_by(MarketData.date.asc())
            
            from database.db_manager import db as db_manager
            df = pd.read_sql(query.statement, db_manager.engine)
            
            if df.empty:
                self.logger.warning(f"No data found in DB for {ticker}")
                return {"cleaned_data": None}
                
            # Set Date as index for indicator calculations
            df.set_index('date', inplace=True)
            
            # 2. Clean data
            df = self._clean_data(df)
            
            # 3. Add indicators
            # We pass a dataframe with capitalized standard names
            indicator_df = df.rename(columns={
                'open': 'Open',
                'high': 'High',
                'low': 'Low',
                'close': 'Close',
                'volume': 'Volume'
            })
            indicator_df = add_all_indicators(indicator_df)
            
            # 4. Handle NaNs generated by indicator lookback periods
            # E.g., a 200 EMA will have 199 NaNs at the start.
            # We drop these as the models need complete rows.
            indicator_df.dropna(inplace=True)
            
            # 5. Normalization (if required for ML)
            if normalize and not indicator_df.empty:
                # We normalize prices and volume, indicators like RSI (0-100) can be normalized separately
                cols_to_norm = ["Open", "High", "Low", "Close", "Volume"]
                indicator_df = normalize_features(indicator_df, cols_to_norm)
                
            self.logger.info(f"Processing complete for {ticker}. Final shape: {indicator_df.shape}")
            
            return {
                "ticker": ticker,
                "rows_processed": len(indicator_df),
                # We return it as a dict orient relative to dates or similar, 
                # but returning DataFrame proxy is cleaner for internal Python flows
                "data": indicator_df 
            }
            
        except Exception as e:
            self.logger.error(f"Error processing data for {ticker}: {e}")
            raise

    def _clean_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Cleans up bad data: Zero volumes, extreme outliers, missing days.
        """
        # Forward fill any missing prices
        df['close'] = df['close'].ffill()
        df['open'] = df['open'].fillna(df['close'])
        df['high'] = df['high'].fillna(df['close'])
        df['low'] = df['low'].fillna(df['close'])
        df['volume'] = df['volume'].fillna(0)
        
        # Replace extreme 0s in prices which might be bad data
        df['close'].replace(0, pd.NA, inplace=True)
        df['close'] = df['close'].ffill()
        
        return df

    def __del__(self):
        if self.session:
            self.session.close()
